Repository FRONTENDBOOTCAMP-13th/Final-02-Twogether, pull requests merged in 2025-08, with the labels that each got.

#112 Q&A 게시판 작성시 제품 목록 불러오기 및 수정 삭제 버튼 수정
  public/images/event/event_8.png
  src/app/community/[boardType]/[id]/page.tsx
  src/app/community/[boardType]/layout.tsx
  src/app/community/[boardType]/page.tsx
  src/app/community/[boardType]/search/page.tsx
  src/app/my-page/[boardType]/[id]/ButtonSection.tsx
  src/app/my-page/[boardType]/[id]/edit/RegistForm.tsx
  src/app/my-page/[boardType]/[id]/page.tsx
  src/app/my-page/[boardType]/new/RegistForm.tsx
  src/app/my-page/[boardType]/page.tsx
  src/components/common/SearchForm.tsx
  src/components/post/ProductName.tsx
  src/data/actions/post.ts
  src/data/functions/post.ts
  src/types/post.ts
Labels: feature

#133 [개발] 상품 상세페이지에 이미지 넣기
  api/dbinit/team/uploadFiles/products_longSleeve_1_model-2.webp
  api/dbinit/team/uploadFiles/products_longSleeve_2_model-3.webp
  api/dbinit/team/uploadFiles/products_longSleeve_3_detail-3.webp
  api/dbinit/team/uploadFiles/products_robe_1_model-3.webp
  api/dbinit/team/uploadFiles/products_robe_3_detail-3.webp
  api/dbinit/team/uploadFiles/products_shortSleeve_2_model-2.webp
  api/dbinit/team/uploadFiles/products_shortSleeve_3_detail-3.webp
  src/app/eventSlider.tsx
  src/app/layout.tsx
  src/app/shop/[productType]/ProductCardItemLayout.tsx
  src/app/shop/[productType]/[id]/Details.tsx
  src/app/shop/[productType]/[id]/Overview.tsx
  src/app/shop/[productType]/[id]/ProductSelect.tsx
  src/app/shop/[productType]/[id]/ProductTabs.tsx
  src/app/shop/[productType]/[id]/ProductTypeIdItem.tsx
  src/app/shop/[productType]/[id]/QnA.tsx
  src/app/shop/[productType]/[id]/Review.tsx
  src/app/shop/[productType]/[id]/ShareBtn.tsx
  src/app/shop/[productType]/[id]/page.tsx
  src/components/common/imgSlider.tsx
  src/components/product/ImagesSwiper.tsx
  src/types/product.ts
Labels: P3, bug, enhancement

#131 [개발] 회원가입 시 이메일 인증 추가
  src/app/(user)/find-email/FindEmailForm.tsx
  src/app/(user)/find-email/page.tsx
  src/app/(user)/login/LoginForm.tsx
  src/app/(user)/login/page.tsx
  src/app/(user)/resend-verification/ResendVerificationForm.tsx
  src/app/(user)/resend-verification/page.tsx
  src/app/(user)/signup/form/SignupForm.tsx
  src/app/(user)/signup/success/page.tsx
  src/app/my-page/edit-profile/form/EditProfileForm.tsx
  src/app/my-page/edit-profile/form/page.tsx
  src/app/my-page/edit-profile/success/page.tsx
  src/app/my-page/edit-profile/verify/VerifyForm.tsx
  src/app/my-page/edit-profile/verify/page.tsx
  src/data/actions/user.ts
  src/stores/useUserStore.ts
  src/types/user.ts
Labels: enhancement, feature

#134 [개발] 페이지네이션 기능 개발
  src/app/community/CommunityPage.tsx
  src/app/community/[boardType]/page.tsx
  src/app/community/[boardType]/search/page.tsx
  src/app/my-page/[boardType]/MyQnaList.tsx
  src/app/my-page/[boardType]/QnaList.tsx
  src/app/my-page/[boardType]/page.tsx
  src/app/my-page/[boardType]/search/QnaSearchClient.tsx
  src/app/my-page/[boardType]/search/page.tsx
  src/components/post/ProductName.tsx
  src/components/post/QnaSearchForm.tsx
  src/components/post/QnaSearchList.tsx
  src/components/post/SearchForm.tsx
  src/data/functions/post.ts
  src/types/api.ts
Labels: enhancement, feature, refactor

#142 [개발] 장바구니 및 주문 로직 개선
  src/app/cart/page.tsx
  src/app/order/page.tsx
  src/app/shop/[productType]/[id]/ProductSelect.tsx
  src/app/shop/[productType]/[id]/ShoppingCartAdd.tsx
  src/components/cart/CartForm.tsx
  src/components/cart/CartItemCard.tsx
  src/components/cart/InfoSection.tsx
  src/components/cart/PriceDetailsSection.tsx
  src/components/order/OrderForm.tsx
  src/components/order/OrderItemCard.tsx
  src/components/order/OrderListSection.tsx
  src/stores/useOrderStore.ts
  src/types/cart.ts
  src/utils/cart.ts
Labels: enhancement

#146 [개발] 주문취소 버튼 -> 주문 상세 버튼으로 변경
  src/app/my-page/order-list/OrderFetcher.tsx
  src/app/my-page/order-list/OrderSummaryCard.tsx
Labels: enhancement

#147 [설정] db data.json 파일 최종본
  api/dbinit/team/data.json
  src/app/shop/[productType]/page.tsx
Labels: feature, documentation

#143 [개발] ProductItem에 링크 및 할인 정보 연결
  src/app/(user)/find-email/FindEmailForm.tsx
  src/app/(user)/resend-verification/ResendVerificationForm.tsx
  src/app/(user)/signup/form/SignupForm.tsx
  src/app/my-page/edit-profile/form/EditProfileForm.tsx
  src/app/my-page/order-list/[orderId]/OrderDetailFetcher.tsx
  src/app/my-page/order-list/[orderId]/ProductItem.tsx
  src/app/my-page/order-list/[orderId]/[productId]/review-post/ReviewPostForm.tsx
  src/app/my-page/order-list/[orderId]/[productId]/review-post/page.tsx
  src/app/my-page/review/ReviewItem.tsx
  src/app/my-page/review/[reviewId]/edit-review/EditReviewForm.tsx
  src/app/my-page/review/[reviewId]/edit-review/page.tsx
  src/app/search/SeachResult.tsx
  src/data/actions/user.ts
Labels: enhancement

#154 [개발] 카카오맵 주소검색 API 적용
  src/components/order/OrderForm.tsx
  src/components/order/ShippingDetailsSection.tsx
  src/data/actions/order.ts
Labels: feature

#156 [버그] 메인 이밴트 슬라이드 높이 조절
  src/app/eventSlider.tsx
Labels: bug

#160 [문서] README 이미지 파일 추가
  README.md
  public/images/readme/aboutus.png
  public/images/readme/cart.png
  public/images/readme/like.png
  public/images/readme/login.png
  public/images/readme/mypage.png
  public/images/readme/notice.png
  public/images/readme/order.png
  public/images/readme/productdetail.png
  public/images/readme/productlist.png
  public/images/readme/qna.png
  public/images/readme/search.png
Labels: documentation
