Repository FRONTENDBOOTCAMP-13th/Final-02-Twogether, pull requests merged in 2025-07, with the labels that each got.

#13 [설정] Lucide 설치 완료
  package-lock.json
  package.json
Labels: P1, enhancement, needs review

#21 [설정] MongoDB 연결 및 초기화, Bruno 세팅 완료
  api/bruno/team/05_게시판(QnA, 공지 등)/folder.bru
  api/bruno/team/06_시스템/folder.bru
  api/bruno/team/bruno.json
  api/bruno/team/environments/twogether.bru
  api/bruno/test/bruno.json
  api/bruno/test/collection.bru
  api/bruno/test/environments/sample.bru
  api/bruno/test/게시물 목록 조회.bru
  api/bruno/test/게시물 상세 조회.bru
  api/bruno/test/게시물에 북마크 추가.bru
  api/bruno/test/로그인.bru
Labels: P1, enhancement, needs review

#25 [개발] 헤더, 푸터, 네비게이션, 버튼 컴포넌트 추가
  src/app/layout.tsx
  src/components/common/Button.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/Navigation.tsx
  src/components/layout/SubHeader.tsx
Labels: feature

#26 [개발] 카테고리 UI 작성 완료
  src/app/brand/page.tsx
  src/app/globals.css
  src/app/menu/page.tsx
Labels: feature

#31 [개발] Zustand 전역 상태관리 구조 설계 및 세팅 완료
  src/constants/.gitkeep
  src/constants/options.ts
  src/stores/.gitkeep
  src/stores/useCartStore.ts
  src/stores/useLikeStore.ts
  src/stores/useModalStore.ts
  src/stores/useUserStore.ts
Labels: P1, feature, needs review

#34 [개발] 찜 페이지 완료
  src/app/imgSlider.tsx
  src/app/like/.gitkeep
  src/app/like/page.tsx
  src/components/product/ProductCard.tsx
Labels: P1, feature

#37 [개발] 로그인/회원가입 페이지 작성
  src/app/(user)/login/page.tsx
  src/app/(user)/signup/form/page.tsx
  src/app/(user)/signup/layout.tsx
  src/app/(user)/signup/success/page.tsx
  src/app/(user)/signup/terms/page.tsx
  src/app/layout.tsx
  src/components/common/CheckBox.tsx
  src/components/common/Input.tsx
  src/components/layout/Header.tsx
  src/components/layout/SubHeader.tsx
Labels: feature

#48 [개발] 404 페이지 작성 완료
  public/images/404/notfound.png
  public/images/404/space.png
  src/app/not-found.tsx
Labels: feature

#49 [개발] 마이페이지 Q&A 페이지 작성
  src/app/my-page/qna/[id]/edit/RegistForm.tsx
  src/app/my-page/qna/[id]/edit/page.tsx
  src/app/my-page/qna/[id]/page.tsx
  src/app/my-page/qna/new/RegistForm.tsx
  src/app/my-page/qna/new/page.tsx
  src/app/my-page/qna/page.tsx
Labels: feature

#50 [개발] 검색 페이지 작성
  src/app/search/SearchMain.tsx
  src/app/search/page.tsx
Labels: feature

#51 [개발] 상세페이지 작성
  api/bruno/team/05_게시판(QnA, 공지 등)/01_목록 조회/게시물 목록 조회.bru
  api/dbinit/team/data.js
  src/app/Mainlayout.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/shop/ProductTypeLayout.tsx
  src/app/shop/ProductTypeList.tsx
  src/app/shop/[productType]/[id]/Details.tsx
  src/app/shop/[productType]/[id]/Overview.tsx
  src/app/shop/[productType]/[id]/ProductTypeIdItme.tsx
  src/app/shop/[productType]/[id]/ProductTypeIdLayout.tsx
  src/app/shop/[productType]/[id]/QnA.tsx
  src/app/shop/[productType]/[id]/Review.tsx
  src/app/shop/[productType]/[id]/ReviewCom.tsx
  src/app/shop/[productType]/[id]/ShoppingCartAdd.tsx
  src/app/shop/[productType]/[id]/layout.tsx
  src/app/shop/[productType]/[id]/page.tsx
  src/app/shop/[productType]/[id]/productSelect.tsx
  src/app/shop/layout.tsx
  src/components/common/imgSlider.tsx
  src/components/product/LikeButton.tsx
  src/components/product/ProductCardItem.tsx
Labels: P1, feature

#44 [개발] 장바구니 페이지 구현 완료
  src/app/cart/.gitkeep
  src/app/cart/page.tsx
  src/components/cart/CartItemCard.tsx
  src/components/cart/CartListItem.tsx
  src/components/cart/CartListSection.tsx
  src/components/cart/Counter.tsx
  src/components/cart/InfoListItem.tsx
  src/components/cart/InfoSection.tsx
  src/components/cart/PriceDetailsSection.tsx
  src/constants/money.ts
  src/stores/useCartStore.ts
  src/utils/cart.ts
Labels: enhancement, feature, needs review

#59 [개발] 주문 페이지 작성 완료
  src/app/order/page.tsx
  src/components/common/CheckBox.tsx
  src/components/order/OrderForm.tsx
  src/components/order/OrderItemCard.tsx
  src/components/order/OrderListSection.tsx
  src/components/order/PaymentOptionSection.tsx
  src/components/order/ShippingDetailsSection.tsx
  src/components/order/TermsListItem.tsx
  src/components/order/TermsSection.tsx
Labels: feature, needs review

#62 [개발] 커뮤니티 페이지 api 서버 연동 페이지네이션 제외
  api/bruno/team/05_게시판(QnA, 공지 등)/01_목록 조회/게시물 목록 조회.bru
  api/bruno/team/05_게시판(QnA, 공지 등)/게시물 등록.bru
  public/images/event/event_5.png
  public/images/event/event_6.png
  public/images/event/event_7.png
  public/images/event/event_8.png
  src/app/community/EventList.tsx
  src/app/community/NoticeList.tsx
  src/app/community/[boardType]/[id]/page.tsx
  src/app/community/[boardType]/page.tsx
  src/data/actions/post.ts
  src/data/functions/post.ts
  src/types/post.ts
Labels: feature

#72 [개발] 마이페이지 Q&A 페이지 API 연동
  src/app/my-page/[boardType]/MyQnaList.tsx
  src/app/my-page/[boardType]/QnaList.tsx
  src/app/my-page/[boardType]/[id]/DeleteForm.tsx
  src/app/my-page/[boardType]/[id]/edit/RegistForm.tsx
  src/app/my-page/[boardType]/[id]/edit/page.tsx
  src/app/my-page/[boardType]/[id]/page.tsx
  src/app/my-page/[boardType]/new/RegistForm.tsx
  src/app/my-page/[boardType]/new/page.tsx
  src/app/my-page/[boardType]/page.tsx
  src/app/my-page/qna/.gitkeep
  src/app/my-page/qna/[id]/edit/RegistForm.tsx
  src/app/my-page/qna/[id]/edit/page.tsx
  src/app/my-page/qna/[id]/page.tsx
  src/app/my-page/qna/new/RegistForm.tsx
  src/app/my-page/qna/new/page.tsx
  src/app/my-page/qna/page.tsx
  src/data/actions/post.ts
  src/data/functions/post.ts
  src/types/post.ts
Labels: feature

#77 [버그] 상품 상세페이지 로딩시 getProduct의 ID 관련 이슈
  src/app/shop/[productType]/ProductCardItemLayout.tsx
  src/app/shop/[productType]/[id]/Details.tsx
  src/app/shop/[productType]/[id]/Overview.tsx
  src/app/shop/[productType]/[id]/ProductTabs.tsx
  src/app/shop/[productType]/[id]/QnA.tsx
  src/app/shop/[productType]/[id]/page.tsx
  src/app/shop/[productType]/page.tsx
  src/data/functions/shop.ts
  src/types/product.ts
Labels: bug

#78 [개발] 상품 상세 페이지 장바구니 API 연동 완료
  src/app/shop/[productType]/[id]/ProductSelect.tsx
  src/app/shop/[productType]/[id]/ShoppingCartAdd.tsx
  src/data/actions/cart.ts
Labels: enhancement, feature

#84 [개발] 개인 정보 수정 API 연동
  public/images/icon/default_profile.svg
  public/images/icon/profile_loading.gif
  src/app/(user)/login/LoginForm.tsx
  src/app/(user)/login/page.tsx
  src/app/(user)/signup/form/SignupForm.tsx
  src/app/(user)/signup/form/page.tsx
  src/app/(user)/signup/success/LoginReplaceButton.tsx
  src/app/(user)/signup/success/page.tsx
  src/app/(user)/signup/terms/TermsForm.tsx
  src/app/(user)/signup/terms/page.tsx
  src/app/my-page/EditProfileImage.tsx
  src/app/my-page/MypageMain.tsx
  src/app/my-page/edit-profile/form/EditProfileForm.tsx
  src/app/my-page/edit-profile/form/page.tsx
  src/app/my-page/edit-profile/layout.tsx
  src/app/my-page/edit-profile/success/ReplaceButton.tsx
  src/app/my-page/edit-profile/success/page.tsx
  src/app/my-page/edit-profile/verify/VerifyForm.tsx
  src/app/my-page/edit-profile/verify/page.tsx
  src/app/my-page/order-list/[orderId]/[productId]/review-post/ReviewPostForm.tsx
  src/app/my-page/order-list/[orderId]/[productId]/review-post/page.tsx
  src/app/my-page/order-list/[orderId]/page.tsx
  src/app/my-page/order-list/page.tsx
  src/app/my-page/page.tsx
  src/app/my-page/review/ReviewImagesModal.tsx
  src/app/my-page/review/[reviewId]/edit-review/EditReviewForm.tsx
  src/app/my-page/review/[reviewId]/edit-review/page.tsx
  src/app/my-page/review/page.tsx
  src/data/actions/user.ts
  src/types/user.ts
Labels: enhancement, feature

#86 [개발] 찜 페이지
  api/bruno/team/01_회원/01_회원가입,로그인/관리자 로그인(_id=1).bru
  api/bruno/team/01_회원/04_회원 정보 조회/지정한 회원 정보 조회(모든 속성).bru
  api/bruno/team/01_회원/folder.bru
  api/bruno/team/02_상품/folder.bru
  api/bruno/team/02_상품/상품 상세 조회.bru
  api/bruno/team/03_찜/folder.bru
  api/bruno/team/03_찜/찜 목록 삭제.bru
  api/bruno/team/03_찜/찜 목록 조회.bru
  api/bruno/team/03_찜/찜 목록 추가.bru
  api/bruno/team/05_게시판(QnA, 공지 등)/folder.bru
  api/bruno/team/06_시스템/folder.bru
  api/dbinit/team/data.js
  src/app/like/LikePageIsUser.tsx
  src/app/like/page.tsx
  src/app/shop/[productType]/[id]/ProductSelect.tsx
  src/app/shop/[productType]/page.tsx
  src/components/layout/Navigation.tsx
  src/components/product/ImagesSwiper.tsx
  src/components/product/LikeAddButton.tsx
  src/components/product/LikeButton.tsx
  src/components/product/LikeDelButton.tsx
  src/components/product/ProductCardItem.tsx
  src/data/actions/like.ts
  src/data/functions/like.ts
  src/types/index.ts
  src/types/like.ts
Labels: feature

#89 [개발] 메인페이지에 best, sale 상품 보이기
  src/app/ProductMainPage.tsx
  src/app/page.tsx
  src/components/product/ProductCardItem.tsx
Labels: feature

#94 [개발] 검색 페이지 API 연동
  src/app/my-page/review/ReviewDeleteForm.tsx
  src/app/my-page/review/ReviewItemNew.tsx
  src/app/search/SeachResult.tsx
  src/app/search/SearchMain.tsx
Labels: P1, feature

#100 [개발] 상품 상세페이지에 리뷰, qna 조회하기
  api/bruno/team/02_구매/구매 상세 조회.bru
  api/bruno/team/02_구매/상품 구매.bru
  api/bruno/team/02_상품/상품 상세 조회.bru
  api/bruno/team/02_상품/상품리뷰/folder.bru
  api/bruno/team/02_상품/상품리뷰/상품리뷰 등록.bru
  api/bruno/team/02_상품/상품리뷰/상품리뷰조회.bru
  api/bruno/team/05_게시판(QnA, 공지 등)/01_목록 조회/게시물 목록 조회.bru
  api/bruno/team/05_게시판(QnA, 공지 등)/01_목록 조회/게시품 목록조회(상품 id).bru
  api/bruno/team/05_게시판(QnA, 공지 등)/게시물 등록.bru
  api/dbinit/team/data.js
  api/dbinit/team/uploadFiles/products_acc_1_detail-1.webp
  api/dbinit/team/uploadFiles/products_acc_2_detail-1.webp
  api/dbinit/team/uploadFiles/products_acc_3_detail-1.webp
  api/dbinit/team/uploadFiles/products_longSleeve_1_detail-1.webp
  api/dbinit/team/uploadFiles/products_longSleeve_2_detail-1.webp
  api/dbinit/team/uploadFiles/products_longSleeve_3_detail-1.webp
  api/dbinit/team/uploadFiles/products_longSleeve_4_detail-1.webp
  api/dbinit/team/uploadFiles/products_longSleeve_5_detail-1.webp
  api/dbinit/team/uploadFiles/products_longSleeve_6_detail-1.webp
  api/dbinit/team/uploadFiles/products_robe_1_detail-1.webp
  api/dbinit/team/uploadFiles/products_robe_2_detail-1.webp
  api/dbinit/team/uploadFiles/products_robe_3_detail-1.webp
  api/dbinit/team/uploadFiles/products_shortSleeve_1_detail-1.webp
  api/dbinit/team/uploadFiles/products_shortSleeve_2_detail-1.webp
  api/dbinit/team/uploadFiles/products_shortSleeve_3_detail-1.webp
  api/dbinit/team/uploadFiles/products_shortSleeve_4_detail-1.webp
  api/dbinit/team/uploadFiles/products_shortSleeve_5_detail-1.webp
  api/dbinit/team/uploadFiles/user-muzi.png
  api/dbinit/team/uploadFiles/user-neo.png
  next.config.ts
  src/app/shop/[productType]/[id]/Details.tsx
  src/app/shop/[productType]/[id]/ProductTabs.tsx
  src/app/shop/[productType]/[id]/QnA.tsx
  src/app/shop/[productType]/[id]/Review.tsx
  src/app/shop/[productType]/[id]/page.tsx
  src/components/common/imgSlider.tsx
  src/data/actions/like.ts
  src/data/functions/like.ts
  src/data/functions/post.ts
  src/data/functions/review.ts
  src/types/post.ts
Labels: P1, feature
